const app=document.getElementById('country-room-app');
const code=document.body.dataset.code;
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safeUrl=(v='')=>{const s=String(v);return /^(https?:\/\/|\.\.\/|#)/.test(s)?s:'#'};
const ext=(url)=>/^https?:\/\//.test(url)?' target="_blank" rel="noopener noreferrer"':'';
function sourceLink(item){const url=safeUrl(item.source_url||item.url||'#');return `<a href="${esc(url)}"${ext(url)}>${esc(item.source||item.producer||'Official source')} ↗</a>`}
function renderIndicator(x){const withheld=x.value==='withheld';return `<article class="indicator${withheld?' withheld':''}"><div class="label">${esc(x.label)}</div><div class="value">${withheld?'Not promoted':esc(x.value)}${!withheld&&x.unit?`<span class="unit">${esc(x.unit)}</span>`:''}</div><dl><dt>Period</dt><dd>${esc(x.period||'—')}</dd><dt>Release</dt><dd>${esc(x.release_date||'—')}</dd><dt>Source</dt><dd>${sourceLink(x)}</dd><dt>Vintage</dt><dd>${esc(x.vintage||'—')}</dd><dt>Definition</dt><dd>${esc(x.definition||'—')}</dd></dl></article>`}
function renderSources(rows){return `<div class="source-table-wrap"><table class="source-table"><thead><tr><th>Domain</th><th>Producer</th><th>Dataset / release</th><th>Frequency</th><th>Format</th><th>Archive quality</th><th>Primary source</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.domain)}</td><td>${esc(x.producer)}</td><td>${esc(x.release)}</td><td>${esc(x.frequency)}</td><td>${esc(x.format)}</td><td><span class="quality ${x.archive_quality==='strong'?'strong':'partial'}">${esc(x.archive_quality)}</span></td><td><a href="${esc(safeUrl(x.url))}"${ext(x.url)}>Open ↗</a></td></tr>`).join('')}</tbody></table></div>`}
function renderNotes(rows){return `<div class="notes-grid">${rows.map(x=>`<article class="measurement-note"><div class="id">${esc(x.id)}</div><h3>${esc(x.question)}</h3><p class="answer">${esc(x.answer)}</p></article>`).join('')}</div>`}
function renderLedger(rows){return `<div class="ledger-wrap"><table class="ledger"><thead><tr><th>Released</th><th>Indicator</th><th>Reference period</th><th>First value / state</th><th>Current value / state</th><th>Revised?</th><th>Original source</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.released)}</td><td>${esc(x.indicator)}</td><td>${esc(x.reference)}</td><td>${esc(x.first)}</td><td>${esc(x.current)}</td><td>${esc(x.revised)}</td><td><a href="${esc(safeUrl(x.url))}"${ext(x.url)}>Open ↗</a></td></tr>`).join('')}</tbody></table></div>`}
function renderFindings(rows){return `<div class="finding-grid">${rows.map(x=>`<article class="finding"><div class="id">${esc(x.id)} · MENA Lab finding</div><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p><div class="why">WHY THIS MATTERS<br>${esc(x.why)}</div></article>`).join('')}</div>`}
function renderProgram(rows){return `<div class="program-list">${rows.map(x=>`<article class="program-item"><div class="id">${esc(x.id)} · ${esc(x.state)}</div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p></article>`).join('')}</div>`}
function renderStatus(x){const fields=[['Primary agencies mapped',x.primary_agencies_mapped],['Active release series',x.active_release_series],['Archived source releases',x.archived_source_releases],['Revision history',x.revision_history],['Definition audit',x.definition_audit],['Independent reproduction',x.independent_reproduction],['Last checked',x.last_checked]];return `<div class="evidence-status"><div class="status-title"><div class="k">Evidence status</div><h3>${esc(document.body.dataset.country)} evidence status</h3><p class="mini">Counts are operational records in this room, not decorative completion scores.</p></div><div class="status-matrix">${fields.map(([a,b])=>`<div class="status-cell"><span>${esc(a)}</span><strong>${esc(b||'—')}</strong></div>`).join('')}</div></div>`}
function renderDownloads(room){const downloads=room.downloads||[];return `<div class="download-panel"><div><div class="k">Machine-readable room</div><h2>Inspect the evidence behind the page.</h2><p>Country-room content is generated from a public registry. Downloads are only shown when a real Lab file already exists.</p></div><div class="download-actions"><a href="../../data/country-intelligence.json">Country intelligence JSON</a>${downloads.map(d=>`<a href="${esc(safeUrl(d.url))}">${esc(d.label)}</a>`).join('')}<a href="../../report-error.html">Report a discrepancy</a></div></div>`}
function render(room){document.title=`${room.country} Evidence Room — MENA Evidence Lab`;app.innerHTML=`
<section class="wrap hero"><div class="country-intro"><div><div class="k">Country evidence room · ${esc(code)}</div><h1>${esc(room.country)}</h1><p class="lede">${esc(room.dek)}</p><div class="room-ribbon"><span class="verified">${esc(room.status)}</span><span>Primary sources first</span><span>Vintage-aware</span><span>No silent imputation</span><a href="../../methods.html">Methods</a></div></div><aside class="room-note"><strong>${esc(room.headline)}</strong><br><br>Every promoted dashboard value carries a reference period, release date where preserved, primary producer, vintage and definition. If that chain is incomplete, the value stays off the dashboard.</aside></div></section>
<nav class="country-nav"><div class="inner"><a href="#dashboard">Dashboard</a><a href="#source-map">Official source map</a><a href="#measurement">Measurement notes</a><a href="#ledger">Release & revision ledger</a><a href="#findings">Lab findings</a><a href="#program">Research program</a><a href="#status">Evidence status</a></div></nav>
<section class="wrap room-section" id="dashboard"><div class="section-head"><h2>What do we know now?</h2><p>Small by design. This is not a generic macro dashboard: metadata and source perimeter are displayed with the number.</p></div><div class="indicator-grid">${room.indicators.map(renderIndicator).join('')}</div></section>
<section class="wrap room-section" id="source-map"><div class="section-head"><h2>Who actually produces the evidence?</h2><p>Official producer, release family, frequency, delivery format and archive quality.</p></div>${renderSources(room.sources)}</section>
<section class="wrap room-section" id="measurement"><div class="section-head"><h2>Measurement notes</h2><p>The part of the room that asks whether two statistics with the same label are actually measuring the same thing.</p></div>${renderNotes(room.measurement_notes)}</section>
<section class="wrap room-section" id="ledger"><div class="section-head"><h2>Release & revision ledger</h2><p>A dated record of what was first released and what the current preserved state says. This is the base layer for “what was knowable on a given date?”</p></div>${renderLedger(room.ledger)}</section>
<section class="wrap room-section" id="findings"><div class="section-head"><h2>Original MENA Lab findings</h2><p>Small, inspectable findings built from the source architecture above. Descriptive unless a causal design is explicitly documented.</p></div>${renderFindings(room.findings)}</section>
<section class="wrap room-section" id="program"><div class="section-head"><h2>Country research program</h2><p>Five named work objects per priority room. State is explicit so planned work is not presented as completed research.</p></div>${renderProgram(room.program)}</section>
<section class="wrap room-section">${renderDownloads(room)}</section>
<section class="wrap room-section" id="status">${renderStatus(room)}<p class="provenance-foot">Room registry updated 17 Aug 2026 · Primary-source links remain authoritative · Errors and replaced source files should be reported through the Lab discrepancy route.</p></section>`}
(async()=>{try{const data=await (await fetch('../../data/country-intelligence.json',{cache:'no-store'})).json();const room=data.rooms&&data.rooms[code];if(!room)throw new Error('Priority country room not found');render(room)}catch(err){app.innerHTML=`<section class="wrap hero"><div class="room-error"><div class="k">Country room unavailable</div><h1>${esc(document.body.dataset.country||code)}</h1><p>${esc(err.message)}</p><a class="card-link" href="../">Back to country rooms →</a></div></section>`}})();